package cachemocks

import (
	"github.com/stretchr/testify/mock"

	"github.com/skipor/memcached/cache"
)

// Cache is an autogenerated mock type for the Cache type
type Cache struct {
	mock.Mock
}

// Delete provides a mock function with given fields: key
func (_m *Cache) Delete(key []byte) bool {
	ret := _m.Called(key)

	var r0 bool
	if rf, ok := ret.Get(0).(func([]byte) bool); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields: key
func (_m *Cache) Get(key ...[]byte) []cache.ItemView {
	ret := _m.Called(key)

	var r0 []cache.ItemView
	if rf, ok := ret.Get(0).(func(...[]byte) []cache.ItemView); ok {
		r0 = rf(key...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cache.ItemView)
		}
	}

	return r0
}

// Touch provides a mock function with given fields: key
func (_m *Cache) Touch(key ...[]byte) {
	ret := _m.Called(key)

	if rf, ok := ret.Get(0).(func(...[]byte)); ok {
		rf(key...)
	}
}

// Set provides a mock function with given fields: i
func (_m *Cache) Set(i cache.Item) {
	_m.Called(i)
}

func (c *Cache) NewGetter(rawCommand []byte) cache.Getter   { return c }
func (c *Cache) NewSetter(rawCommand []byte) cache.Setter   { return c }
func (c *Cache) NewDeleter(rawCommand []byte) cache.Deleter { return c }

var _ cache.Cache = (*Cache)(nil)
var _ cache.View = (*Cache)(nil)
