package aof

import mock "github.com/stretchr/testify/mock"

// mockFlusher is an autogenerated mock type for the flusher type
type mockFlusher struct {
	mock.Mock
}

// Flush provides a mock function with given fields:
func (_m *mockFlusher) Flush() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ flusher = (*mockFlusher)(nil)
